# Generated by Django 4.0.2 on 2022-04-07 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0005_delete_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='project_logos/')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default=('Public', 'Public'), max_length=7)),
                ('description', models.TextField()),
                ('socials', models.ManyToManyField(to='auth_app.SocialMedia')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('task_description', models.TextField()),
                ('task_energy', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Moderator', 'Moderator'), ('Member', 'Member'), ('GUEST', 'GUEST')], max_length=9)),
                ('projects', models.ManyToManyField(to='main.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
