# Generated by Django 4.0.2 on 2022-04-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_member_role_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default=('Public', 'Public'), max_length=50),
        ),
    ]
