# Generated by Django 4.0.2 on 2022-04-08 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_energy',
            new_name='energy',
        ),
        migrations.AddField(
            model_name='tasks',
            name='created_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
