# Generated by Django 4.0.2 on 2022-04-09 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tasklist_tasks_tasklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='tasklist',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='tasks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tasks'),
            preserve_default=False,
        ),
    ]
