# Generated by Django 4.0.2 on 2022-04-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_tasks_tasklist_tasklist_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='tasks',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tasklist'),
            preserve_default=False,
        ),
    ]
