# Generated by Django 4.0.2 on 2022-04-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_tasks_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
            preserve_default=False,
        ),
    ]
