# Generated by Django 4.0.2 on 2022-04-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_tasklist_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
