# Generated by Django 4.0.2 on 2022-04-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tasks_is_done'),
        ('chat', '0002_remove_messages_messages_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
            preserve_default=False,
        ),
    ]
