# Generated by Django 4.0.2 on 2022-04-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tasks_is_done'),
        ('chat', '0004_remove_chat_messages_messages_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.member'),
            preserve_default=False,
        ),
    ]
