# Generated by Django 4.0.2 on 2022-04-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chat_users_chat_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='users',
            new_name='members',
        ),
    ]
