# Generated by Django 4.0.2 on 2022-04-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_users_chat_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
