# Generated by Django 4.0.2 on 2022-04-01 11:07

import datetime
from django.db import migrations, models
import tasktell.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[tasktell.common.validators.FileMaxSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[tasktell.common.validators.MinDateValidator(datetime.date(1935, 1, 1))]),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('email', 'user')},
        ),
    ]
