# Generated by Django 4.0.2 on 2022-04-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('facebook', models.URLField()),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='socials',
            field=models.ManyToManyField(to='auth_app.SocialMedia'),
        ),
    ]
