# Generated by Django 4.0.2 on 2022-04-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_members_socialmedia_profile_socials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
