# Generated by Django 4.0.2 on 2022-04-29 11:56

from django.db import migrations, models
import tasktell.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[tasktell.common.validators.FileMaxSizeValidator(5)]),
        ),
    ]
